baseURL = "https://sosna.de/"
title = "Alexander Sosna"
theme = "hugo-coder"
languageCode = "en"
defaultcontentlanguage = "en"

paginate = 40
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Alexander Sosna"
  info = "human"
  description = "Alexander Sosna's personal website"
  keywords = "Alexander Sosna,PostgreSQL,Open Source,Databases,Project Manager"
  avatarurl = "img/Alexander-Sosna.jpg"
  #gravatar = "alexander@sosna.de"

  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  rtl = false
  math = false

  footercontent = ""
  hideFooter = true
  hidecredits = true
  hidecopyright = true
  since = 2019

# Social links
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 1
    url = "https://gitlab.com/xxorde/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/xxorde/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/xxorde/"
[[params.social]]
    name = "PGP-Key"
    icon = "fas fa-key fa-2x"
    weight = 4
    url = "https://pgp.key-server.io/pks/lookup?op=vindex&search=0x957CB30686FDFB1245BB3933565A080331E616C2"
[[params.social]]
    name = "Xing"
    icon = "fab fa-xing fa-2x"
    weight = 5
    url = "https://www.xing.com/profile/Alexander_Sosna2"
[[params.social]]
    name = "linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 6
    url = "https://www.linkedin.com/in/alexander-sosna-7193688b/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
[[menu.main]]
    name = "Impressum"
    weight = 2
    url = "/impressum/"
